language: objective-c
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.2

branches:
except:
- v3

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=SwiftyVK.xcworkspace

  - MAC_SCHEME="SwiftyVK-Example-OSX"

  - IOS_SCHEME="SwiftyVK-Example-iOS"
  - IOS_DESTANATION="platform=iOS Simulator,OS=10.3.1,name=iPhone 7 Plus"

before_install:
  - pwd
  - ls -la
  - ./.install_swiftlint.sh
  - swiftlint lint --path ./Library --config ./Library/.swiftlint.yml --strict


install:
  - gem install xcpretty-travis-formatter
  - cd Example
  - carthage update --platform ios,mac
  - cd ..
  
script:
  - set -o pipefail
  - xcodebuild -workspace SwiftyVK.xcworkspace -scheme "$IOS_SCHEME" -destination "$IOS_DESTANATION" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" -enableCodeCoverage YES build-for-testing test-without-building | xcpretty -f `xcpretty-travis-formatter`
  - xcodebuild -workspace "$WORKSPACE" -scheme "$MAC_SCHEME" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" ENABLE_TESTABILITY=YES -enableCodeCoverage YES build-for-testing test-without-building | xcpretty -f `xcpretty-travis-formatter`

after_success:
- bash <(curl -s https://codecov.io/bash)
