name: _Lint

on:
  workflow_call:
    
jobs:
  lint:
    runs-on: ${{ vars.MACOS_RUNNER }}
    steps:
      - uses: actions/checkout@v4
      - uses: cirruslabs/swiftlint-action@v1
        with:
          version: latest
